### PR TITLE
Uncaught exceptions aren't catched or rejected

### LINKED ISSUE #110: Uncaught exceptions of transformations cause stale image loading
This is a really neat library.

E.g. IE throws this error for huge images:

> SCRIPT16389: Unspecified error.

I'm sure the reason is maximum size restrictions of `<canvas />`:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#Maximum_canvas_size
- https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

A `try/catch` around [`drawImage` should handle thrown exceptions](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage#Exceptions_thrown), like at this line:
https://github.com/blueimp/JavaScript-Load-Image/blob/b14e2df0a0fbcbc5ac2a44d4e399709dd69ba9a4/js/load-image-scale.js#L106

Free high res images can be found here:
https://effigis.com/en/solutions/satellite-images/satellite-image-samples/

load-image-ie-unspecified-error

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #110

### CODE REVIEW

File: js/load-image-scale.js [hunk 1]
```diff
@@ -96,25 +96,29 @@
...
-      ctx.imageSmoothingQuality = options.imageSmoothingQuality
+    try {
+      var ctx = canvas.getContext('2d')
+      if (options.imageSmoothingEnabled === false) {
+        ctx.msImageSmoothingEnabled = false
+        ctx.imageSmoothingEnabled = false
+      } else if (options.imageSmoothingQuality) {
+        ctx.imageSmoothingQuality = options.imageSmoothingQuality
+      }
+      ctx.drawImage(
```
Comment (AndyOGo) [inline js/load-image-scale.js:107]: @blueimp `drwaImage` may throw several exceptions, like fro too huge images.

In case that happens the Promise should reject or the callback api should have an `type === 'error'`.
How is the best way to move this error up?

**Review by AndyOGo — COMMENTED** [review]
Please see my question.

File: js/load-image-scale.js [hunk 2]
```diff
@@ -38,9 +38,17 @@
...
 
   loadImage.transform = function (img, options, callback, file, data) {
+    var scaleImg
+
+    try {
+      scaleImg = loadImage.scale(img, options, data)
+    } catch (error) {
+      scaleImg = error
+    }
+
```
Comment (AndyOGo) [inline js/load-image-scale.js:48]: @blueimp 
Do you think this is a good place to handle uncaught exceptions?
Im considering maybe it's better to handle it for all in the original transform 🤔

File: js/load-image.js [hunk 3]
```diff
@@ -45,6 +45,9 @@
           // Not using Promises
           if (resolve) resolve(img, data)
           return
+        } else if (img instanceof Error) {
+          reject(img);
+          return;
```
Comment (AndyOGo) [inline js/load-image.js:50]: @blueimp `reject` was never called here

File: js/load-image.js [hunk 4]
```diff
@@ -159,10 +162,15 @@
...
-    })
+
+    try {
+      loadImage.transform(img, options, callback, file, {
+        originalWidth: img.naturalWidth || img.width,
+        originalHeight: img.naturalHeight || img.height
+      })
+    } catch (error) {
+      callback(error)
+    }
```
Comment (AndyOGo) [inline js/load-image.js:173]: @blueimp This should now hanlde any uncaught exceptions in any transformations, if I understood the system correctly 🤔

File: js/load-image.js (hunk 3 above)
Comment (AndyOGo) [inline js/load-image.js:50]: @blueimp `reject` was never called here

File: js/load-image.js (hunk 4 above)
Comment (AndyOGo) [inline js/load-image.js:173]: @blueimp This should now hanlde any uncaught exceptions in any transformations, if I understood the system correctly 🤔

**Review by AndyOGo — COMMENTED** [review]
@blueimp Please see my fix for uncaught exceptions

File: js/load-image.js (hunk 3 above)
Comment (blueimp) [reply js/load-image.js]: I did not consider exceptions in the transformation call previously, so that's a necessary addition now that exceptions can bubble up through the resoleWrapper as well.

File: js/load-image-scale.js (hunk 1 above)
Comment (blueimp) [reply js/load-image-scale.js]: For the Promise style API, if the result is an error, it should always reject, so your proposed solution is correct.

File: js/load-image.js (hunk 4 above)
Comment (blueimp) [reply js/load-image.js:173]: Yes, that's the right location for the `try...catch` wrapper. :)

Comment (AndyOGo) [reply js/load-image.js:173]: Great. Any tests you would like to be added?

Comment (blueimp) [reply js/load-image.js:173]: I think it's fine to include this with just the existing tests.

Although it would be good to test this specific scenario (huge canvas sizes) as well, the tradeoff would likely be largely increased memory requirements for running the tests.

Comment (blueimp) [reply js/load-image.js:173]: One other item I'm still thinking about though is that the Promise executor already has an implicit `try...catch` around it, so it's only necessary for the callback style.
I might add this improvement after the merge though, since it requires some restructuring.

**Comment by blueimp** [comment]
Thanks for your report and for providing a solution @AndyOGo. :)

**Comment by blueimp** [comment]
One last request, please squash your commits into a single one (technically this is possible via GitHub's UI as well, but that would remove your authorship information from the commit, which I wanna avoid).

File: js/load-image.js (hunk 4 above)
Comment (AndyOGo) [reply js/load-image.js:173]: hmh, I used the Promise API, but `.catch()` hanlder wasn't called 🤔

Comment (blueimp) [reply js/load-image.js:173]: You're right, the Promise executor cannot catch errors that happen asynchronously.
So everything is fine as is. :)

**Comment by AndyOGo** [comment]
@blueimp Thank you for your feedback.
I sqashed them.

**Comment by blueimp** [comment]
Thanks again! 👍
